# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    role_hierarchy:

         ROLE_VIP: [ROLE_USER]
         ROLE_PERSONAL: [ROLE_VIP]
         ROLE_ADMIN: [ROLE_PERSONAL]

    encoders:
         AppBundle\Entity\Asmuo:
             algorithm: bcrypt
       # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    providers:
        db_provider:
          entity:
            class: AppBundle:Asmuo
            property: elPastas

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false



        main:
            anonymous: ~
            pattern: ^/
            provider: db_provider

            form_login:
                login_path: login
                check_path: login
                default_target_path: homepage
                always_use_default_target_path: true
            anonymous: ~
            logout:
               path:   /logout
               target: / # activate different ways to authenticate
    access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
            - { path: ^/homepage, role: "ROLE_USER"}
            - {path: /admin, role: "ROLE_ADMIN"}
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
